# Example configuration file for recipetracker
# You can use ${ENV_VAR} to substitute environment variables
server:
  port: "${PORT:-8080}"
git:
  repository: "${PORT:-db/}"
  remote: ssh://git@github.com/JonasMH/recipes-testing.git
  sshKeyPath: "../../.secrets/id_ed25519"
frontend:
  enable_proxy: true
